# Generated by Django 2.2.10 on 2020-02-11 10:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('points_balance', models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='user_id',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
    ]
